config/routes.rb
Rails.application.routes.draw do
  root 'threaders#index'
  resources :threaders do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :threader
end

app/models/threader.rb
class Threader < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @threader = Threader.find(params[:threader_id])
        @comment = @threader.comments.create(comment_params)
        redirect_to threader_path(@threader)
    end

    def destroy
        @threader = Threader.find(params[:threader_id])
        @comment = @threader.comments.find(params[:id])
        @comment.destroy
        redirect_to threader_path(@threader)
    end

    private
     def comment_params
        params.require(:comment).permit(:commenter, :body)
     end
end

app/controllers/threaders_controller.rb
class ThreadersController < ApplicationController
  def index
      @threaders = Threader.all
  end

  def show
      @threader = Threader.find(params[:id])
  end

  def new
      @threader = Threader.new
  end

  def edit
      @threader = Threader.find(params[:id])
  end

  def create
      @threader = Threader.new(thread_params)

      if @threader.save
          redirect_to @threader
      else
          render 'new'
      end
  end

  def update
      @threader = Threader.find(params[:id])

      if @threader.update(thread_params)
          redirect_to @threader
      else
          render 'edit'
      end
  end

  def destroy
      @threader = Threader.find(params[:id])
      @threader.destroy

      redirect_to threaders_path
  end

  private
      def thread_params
          params.require(:threader).permit(:title, :text)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/threaders_helper.rb
module ThreadersHelper
end

app/views/comments/_comment.html.erb
<div class="card card-body">
<p>
 <strong>Commenter</strong>
 <%= comment.commenter %>
</p>

<p>
 <strong>Comment</strong>
 <%= comment.body %>
</p>

<p>
 <%= link_to 'Delete', [comment.threader, comment],method: :delete, data:{confirm: 'Are you sure?' },class:'btn btn-outline-danger'%>
</p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @threader, @threader.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter ,class:'form-control' %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body ,class:'form-control' %>
    </p>
    <p>
      <%= form.submit 'Comment',class:'btn btn-outline-warning' %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/threaders/_form.html.erb
<%= form_with scope: :threader, url: threaders_path, local: true do |form| %>
  <% if @threader.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@threader.errors.count, "error") %> prohibited
      this threader from being saved:</h2>
    <ul>
    <% @threader.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title ,class:'form-control'%>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text ,class:'form-control'%>
  </p>

  <p>
    <%= form.submit 'Post',class:'btn btn-outline-danger'%>
  </p>
<% end %>

app/views/threaders/edit.html.erb
<%= render 'form' %>

<%= link_to '<<', threaders_path ,class:'btn btn-dark'%>

app/views/threaders/index.html.erb
<div class="form-inline">
<h1 class="mr-auto">Bulletinboard App</h1>
<%= link_to 'New threader', new_threader_path ,class:'btn btn-outline-primary'%>
</div>

<div class="row">
<% @threaders.each do |threader| %>
  <div class="col-sm-12 card mt-2">
  <div class="card-body">
  <%= threader.title %><br>
  <%= threader.text %><br>
  <div class="text-right">
  <%= link_to 'Read More...',threader_path(threader) %>
  <%= link_to 'Destroy',threader_path(threader),method: :delete, data: {confirm: 'Are you sure?'} ,class:'btn btn-danger'%>
  </div>
  </div>
  </div>
<% end %>
</div>

app/views/threaders/new.html.erb
<%= render 'form' %>

<%= link_to '<<', threaders_path ,class:'btn btn-dark'%>

app/views/threaders/show.html.erb
<div class="card card-header">
<p>
 <strong>Title:</strong>
 <%= @threader.title %>
</p>

<p>
 <strong>Text:</strong>
 <%= @threader.text %>
</p>

<p>
<%= link_to 'Edit', edit_threader_path(@threader) ,class:'btn btn-outline-success'%>
</p>
</div>


<%= render @threader.comments %>
<%= render "comments/form" %>

<%= link_to '<<', threaders_path ,class:'btn btn-dark'%>